name: flutter_mono_repo
description: "A new Flutter package project."
version: 0.0.1
homepage: https://www.baidu.com


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    melos: ^6.2.0
    dio: ^5.0.0


